### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by sohrabhs** [alex8088/node-signalr#1]
Thanks for your helpful package, but I am working with an SignalR API that needs to authenticate through a hub and get a token to put it in the next queryStrings to send to other hub methods. I couldn't find an equivalent way to do that.
I really appreciated to here from you,
Best.

**Comment by alex8088** [comment]
> Thanks for your helpful package, but I am working with an SignalR API that needs to authenticate through a hub and get a token to put it in the next queryStrings to send to other hub methods. I couldn't find an equivalent way to do that.
> I really appreciated to here from you,
> Best.

@sohrabhs 
Hi, sorry to reply you too late.
A hub uses websocket to send and receive messages. You can only use token as a parameter but not querystring.
One way is to authenticate through headers.Of course, this way requires server support.
