### ISSUE TITLE
SSL protocol options

### ISSUE THREAD

**Issue by rafateruya** [alex8088/node-signalr#4]
I'm working in a project which needs connection with a server with self signed certificate.
It would be great if in client configuration, we had the option to set an agent, that is used in https requests. Something like this:

## Client Config
```
import { Agent } from 'https'

client.agent = new Agent({ pfx: 'pfx', passphrase: 'passphrase' })
```

## Negotiate
```
let negotiateRequestOptions = url.parse(`${this.url}/negotiate?${query}`, true)
negotiateRequestOptions.headers = this.headers
negotiateRequestOptions.timeout = this.requestTimeout || 5000
// adding custom agent here
negotiateRequestOptions.agent = this.agent
let req = this.request.get(negotiateRequestOptions, (res) => {
...
```

Thx !

**Comment by alex8088** [comment]
@rafateruya new ver 2.0.6, try it

**Comment by Kerwood** [comment]
Trying out ver 2.0.6
I'm using the `rejectUnauthorized` property but I cent seem to get it working.
Here's my code.
```
const https = require('https')
const signalr = require('node-signalr')

const client = new signalr.client('https://<hostname>/signalr', ['Hub'])
client.agent = new https.Agent({ rejectUnauthorized: false })

client.on('connected', () => {
  console.log('SignalR client connected.')
})
client.on('reconnecting', (count) => {
  console.log(`SignalR client reconnecting(${count}).`)
})
client.on('disconnected', (code) => {
  console.log(`SignalR client disconnected(${code}).`)
})
client.on('error', (code, ex) => {
  console.log(`SignalR client connect error: ${code} ${ex}.`)
})

client.start()
```

This is the error.
```
SignalR client connect error: Socket error Error: unable to verify the first certificate.
SignalR client disconnected(failed).
```

Am I doing something wrong ?

**Comment by alex8088** [comment]
> Trying out ver 2.0.6
> I'm using the `rejectUnauthorized` property but I cent seem to get it working.
> Here's my code.
> 
> ```
> const https = require('https')
> const signalr = require('node-signalr')
> 
> const client = new signalr.client('https://<hostname>/signalr', ['Hub'])
> client.agent = new https.Agent({ rejectUnauthorized: false })
> 
> client.on('connected', () => {
>   console.log('SignalR client connected.')
> })
> client.on('reconnecting', (count) => {
>   console.log(`SignalR client reconnecting(${count}).`)
> })
> client.on('disconnected', (code) => {
>   console.log(`SignalR client disconnected(${code}).`)
> })
> client.on('error', (code, ex) => {
>   console.log(`SignalR client connect error: ${code} ${ex}.`)
> })
> 
> client.start()
> ```
> 
> This is the error.
> 
> ```
> SignalR client connect error: Socket error Error: unable to verify the first certificate.
> SignalR client disconnected(failed).
> ```
> 
> Am I doing something wrong ?

Do you use self signed certificate ?

**Comment by Kerwood** [comment]
Yes I do. The webserver is some proprietary software that crates its own certificates.

**Comment by alex8088** [comment]
> Yes I do. The webserver is some proprietary software that crates its own certificates.

see https://stackoverflow.com/questions/31673587/error-unable-to-verify-the-first-certificate-in-nodejs
